"""Independent synthetic source/port evidence; run once in each pinned environment.

The inputs are analytic Gaussian-convolved decays, not generated by either engine.
The source full-model fitted data is reconstructed by named CLP dimensions because
v0.7 has a documented residual reshape defect. Raw fitted data is retained too.
"""

from __future__ import annotations

import argparse
import json
import subprocess
from pathlib import Path

import numpy as np
import xarray as xr
from scipy.special import erfc


def run(branch: str, output: Path) -> None:
    import glotaran
    from glotaran.parameter import Parameters

    output.mkdir(parents=True, exist_ok=False)
    time = np.linspace(-0.5, 12, 101)
    spectral = np.linspace(450, 650, 17)
    rates = np.array([0.4, 0.9])
    sigma = 0.1
    local = np.column_stack([
        0.25 * np.exp(0.5 * (rate * sigma) ** 2 - rate * time)
        * erfc((rate * sigma**2 - time) / (np.sqrt(2) * sigma))
        for rate in rates
    ])
    global_matrix = np.column_stack([
        np.exp(-np.log(2) * (2 * (spectral - center) / width) ** 2)
        for center, width in [(500, 45), (580, 65)]
    ])
    wanted = local @ np.diag([2., 3.]) @ global_matrix.T
    noise = 1e-5 * np.sin(np.arange(wanted.size).reshape(wanted.shape))
    parameters = Parameters.from_list([
        ["k1", .45], ["k2", .85], ["one", 1., {"vary": False}],
        ["zero", 0., {"vary": False}], ["sigma", sigma, {"vary": False}],
        ["center1", 500., {"vary": False}], ["center2", 580., {"vary": False}],
        ["width1", 45., {"vary": False}], ["width2", 65., {"vary": False}],
    ])
    base = {
        "default_megacomplex": "decay",
        "megacomplex": {
            "kinetic": {"type": "decay", "k_matrix": ["rates"]},
            "spectral": {"type": "spectral", "shape": {"s1": "g1", "s2": "g2"}},
        },
        "k_matrix": {"rates": {"matrix": {"(s1, s1)": "k1", "(s2, s2)": "k2"}}},
        "initial_concentration": {"initial": {"compartments": ["s1", "s2"], "parameters": ["one", "one"]}},
        "irf": {"irf": {"type": "gaussian", "center": "zero", "width": "sigma"}},
        "shape": {
            "g1": {"type": "gaussian", "amplitude": "one", "location": "center1", "width": "width1"},
            "g2": {"type": "gaussian", "amplitude": "one", "location": "center2", "width": "width2"},
        },
    }
    summaries = {}
    arrays = {"analytic": wanted, "noise": noise, "time": time, "spectral": spectral}
    for case in ["paired", "linked_scale", "unlinked_scale"]:
        import copy
        spec = copy.deepcopy(base)
        dataset = {"megacomplex": ["kinetic"], "initial_concentration": "initial", "irf": "irf"}
        datasets = {}
        if case == "paired":
            dataset.update(global_megacomplex=["spectral"], single_amplitude_model=True)
            spec["dataset"] = {"data": dataset}
            datasets["data"] = xr.DataArray(wanted + noise, dims=("time", "spectral"), coords={"time": time, "spectral": spectral})
        else:
            spec["dataset_groups"] = {"default": {"link_clp": case == "linked_scale"}}
            spec["dataset"] = {}
            for index, label in enumerate(["first", "second"]):
                scales = np.linspace(1 + index, 2 + index, len(spectral))
                labels = []
                for n, value in enumerate(scales):
                    parameter_label = f"scale{index}_{n}"
                    labels.append(parameter_label)
                    from glotaran.parameter import Parameter
                    # Both versions expose a label-keyed parameter store constructor.
                    parameters = Parameters({p.label: p for p in parameters.all()} | {
                        parameter_label: Parameter(label=parameter_label, value=float(value), vary=False)})
                spec["dataset"][label] = dataset | {"scale_list": labels}
                datasets[label] = xr.DataArray((wanted + noise) * scales, dims=("time", "spectral"), coords={"time": time, "spectral": spectral})
        if branch == "source":
            from glotaran.io import load_model
            import yaml
            from glotaran.project import Scheme
            from glotaran.optimization.optimize import optimize
            model = load_model(yaml.safe_dump(spec, sort_keys=False), format_name="yml_str")
            result = optimize(Scheme(model=model, parameters=parameters.copy(), data=datasets,
                                     maximum_number_function_evaluations=40), verbose=False, raise_exception=True)
            for label, data in result.data.items():
                fitted = data.fitted_data
                if case == "paired":
                    fitted = xr.dot(xr.dot(data.global_matrix, data.clp, dim="global_clp_label"), data.matrix, dim="clp_label")
                arrays[f"{case}_{label}_fit"] = fitted.transpose("time", "spectral").values
                arrays[f"{case}_{label}_raw_fit"] = data.fitted_data.transpose("time", "spectral").values
            summaries[case] = {"nfev": result.number_of_function_evaluations, "number_of_clps": result.number_of_clps,
                               "rates": [result.optimized_parameters.get(k).value for k in ["k1", "k2"]]}
        else:
            from validation.case_studies.migrate import convert_model
            from glotaran.project.scheme import Scheme
            converted, _ = convert_model(spec, Path("synthetic-scale-list.yml"))
            result = Scheme.from_dict(converted).optimize(parameters.copy(), datasets,
                maximum_number_function_evaluations=40, verbose=False, raise_exception=True)
            for label, data in result.optimization_results.items():
                arrays[f"{case}_{label}_fit"] = data.fitted_data.transpose("time", "spectral").values
            summaries[case] = {"nfev": result.optimization_info.number_of_function_evaluations,
                               "number_of_clps": result.optimization_info.number_of_clps,
                               "rates": [result.optimized_parameters.get(k).value for k in ["k1", "k2"]]}
    source_root = Path(glotaran.__file__).resolve().parent.parent
    summaries["source"] = {"package": str(glotaran.__file__), "version": glotaran.__version__,
        "revision": subprocess.check_output(["git", "-C", str(source_root), "rev-parse", "HEAD"], text=True).strip()}
    np.savez(output / "arrays.npz", **arrays)
    (output / "summary.json").write_text(json.dumps(summaries, indent=2), encoding="utf-8")
    print(json.dumps(summaries, indent=2))


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--branch", choices=["source", "staging"], required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    run(args.branch, args.output)

